server:
  port: 8081
spring:
  application:
    name: czrpc-demo-provider
czrpc:
  # 应用级别的配置项
  app:
    applicationId: czrpc-demo
    namespace: public
    env: dev
  #  服务元信息，灰度打标用 - [provider only]
  provider:
    gray: false
    dc: bj
    unit: 001
    online: true
    trafficControl: 20
  # 注册中心配置
  # 使用 zookeeper
  zookeeper:
    server: localhost:2181
    root: czrpc
  # 使用 czRegistry
  czregistry:
    servers: http://127.0.0.1:9090/
logging:
  level:
    root: info
    com.cz: debug