server:
  port: 8088
spring:
  application:
    name: czrpc-demo-consumer
czrpc:
  # 应用级别的配置项
  app:
    applicationId: czrpc-demo
    namespace: public
    env: dev
  consumer:
    retries: 3
    retryTimeout: 1000
    grayRatio: 0
    halfOpenInitialDelay: 10
    halfOpenDelay: 60
    faultLimit: 10
  # 注册中心配置
  # 使用 zookeeper
  zookeeper:
    server: localhost:2181
    root: czrpc
  # 使用 czRegistry
  czRegistry:
    servers:
      - http://127.0.0.1:9090
#      - http://127.0.0.1:9091
#      - http://127.0.0.1:9092


logging:
  level:
    root: info
    com.cz: info
