server:
  port: 8088
spring:
  application:
    name: czrpc-demo-consumer
czrpc:
  id: czrpc-demo
  namespace: public
  env: dev
  retries: 3
  params:
    invokeTimeout: 3000
  #  服务元信息，灰度打标用 - [consumer only]
  metas:
    grayRadio: 10 # 灰度 - 流量调拨比重 0-100
  #    注册中心配置
  zkConfig:
    server: localhost:2181
    root: czrpc
  isolate:
    halfOpen:
      initialDelay: 10
      delay: 60

logging:
  level:
    root: info
    com.cz: info
