server:
  port: 8088
spring:
  application:
    name: czrpc-demo-consumer
czrpc:
  id: czrpc-demo
  namespace: public
  env: dev
  retries: 3
  params:
    invokeTimeout: 3000
  rpcVersion: 1.0.0
  zkConfig:
    server: localhost:2181
    root: czrpc
  isolate:
    halfOpen:
      initialDelay: 10
      delay: 60

logging:
  level:
    root: info
    com.cz: info
