server:
  port: 8088
spring:
  application:
    name: czrpc-demo-consumer
czrpc:
  id: czrpc-demo
  namespace: public
  env: dev
  rpcVersion: 1.0.0
  zkConfig:
    server: localhost:2181
    root: czrpc
logging:
  level:
    root: info
    com.cz: info
