server:
  port: 8088
spring:
  application:
    name: czrpc-demo-consumer
czrpc:
  # 应用级别的配置项
  app:
    applicationId: czrpc-demo
    namespace: public
    env: dev
  consumer:
    # 重试机制
    retries: 3
    retryTimeout: 1000
    # 灰度流量调拨比重
    grayRatio: 10
    # 故障隔离与半开探活
    halfOpenInitialDelay: 10
    halfOpenDelay: 60
    faultLimit: 10
  # 注册中心配置
  registryCenter:
    server: localhost:2181
    root: czrpc


logging:
  level:
    root: info
    com.cz: info
